[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/api/*"
  to = "https://queue-management-system-vp5s.onrender.com/:splat"
  status = 200
  force = true
